export function uiList() {
  return [
    //抖你>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
      img: 'dn/level.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/myLevel/App.vue',
      url: 'https://h5.douni.com/h5__test/myLevel.html',
      app: '抖你',
      desc: '等级',
    },
    {
      img: 'dn/affinity.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/affinity/App.vue',
      url: 'https://h5.douni.com/h5__test/affinity.html',
      app: '抖你',
      desc: '亲密',
    },
    {
      img: 'dn/affinity2.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/affinity2/App.vue',
      url: 'https://h5.douni.com/h5__test/affinity2.html',
      app: '抖你',
      desc: '亲密、弹幕、swiper',
    },
    {
      img: 'dn/mbox.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/misteryBox/App.vue',
      url: 'https://h5.douni.com/h5__test/misteryBox.html',
      app: '抖你',
      desc: '盲盒、上传、弹幕、input',
    },
    {
      img: 'dn/apar.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/apartment/App.vue',
      url: 'https://h5.douni.com/h5__test/apartment.html',
      app: '抖你',
      desc: '公寓、恋爱',
    },
    {
      img: 'dn/chicken.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/chicken/App.vue',
      url: 'https://h5.douni.com/h5__test/chicken.html',
      app: '抖你',
      desc: '榜单、tab、进度、PK',
    },
    {
      img: 'dn/card.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/bindCard/App.vue',
      url: 'https://h5.douni.com/h5__test/bindCard.html',
      app: '抖你',
      desc: '绑定、input',
    },
    {
      img: 'dn/ggao.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/bulletin/App.vue',
      url: 'https://h5.douni.com/h5__test/bulletin.html',
      app: '抖你',
      desc: '公告、列表',
    },
    {
      img: 'dn/aicp.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/cp/App.vue',
      url: 'https://h5.douni.com/h5__test/cp.html',
      app: '抖你',
      desc: '公告、列表',
    },
    {
      img: 'dn/dtask.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/dayTask/App.vue',
      url: 'https://h5.douni.com/h5__test/dayTask.html',
      app: '抖你',
      desc: '半屏、任务、计时',
    },
    {
      img: 'dn/xdlottery.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/heartLottery/App.vue',
      url: 'https://h5.douni.com/h5__test/heartLottery.html',
      app: '抖你',
      desc: '抽奖、转动',
    },
    {
      img: 'dn/snow.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/iceSnow/App.vue',
      url: 'https://h5.douni.com/h5__test/iceSnow.html',
      app: '抖你',
      desc: '冰雪、领取、弹窗、明细',
    },
    {
      img: 'dn/papler.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/misteryBoxPapler/App.vue',
      url: 'https://h5.douni.com/h5__test/misteryBoxPapler.html',
      app: '抖你',
      desc: 'tab、明细、聊天、纸条',
    },
    {
      img: 'dn/nobility.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/nobility/App.vue',
      url: 'https://h5.douni.com/h5__test/nobility.html',
      app: '抖你',
      desc: '支付、弹窗、轮播、swiper、tab、明细',
    },
    {
      img: 'dn/plane.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/paperPlane/App.vue',
      url: 'https://h5.douni.com/h5__test/paperPlane.html',
      app: '抖你',
      desc: '弹窗、弹幕、tab、input',
    },
    {
      img: 'dn/pay1.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/payReward/App.vue',
      url: 'https://h5.douni.com/h5__test/payReward.html',
      app: '抖你',
      desc: '弹窗、规则、box',
    },
    {
      img: 'dn/quality.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/quality/App.vue',
      url: 'https://h5.douni.com/h5__test/quality.html',
      app: '抖你',
      desc: '表格、兑换、box',
    },
    {
      img: 'dn/recharge.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/recharge/App.vue',
      url: 'https://h5.douni.com/h5__test/recharge.html',
      app: '抖你',
      desc: '充值、支付、box',
    },
    {
      img: 'dn/richClub.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/richClub/App.vue',
      url: 'https://h5.douni.com/h5__test/richClub.html',
      app: '抖你',
      desc: 'tab、排行、弹幕、弹窗、进度条、box',
    },
    {
      img: 'dn/task.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/task/App.vue',
      url: 'https://h5.douni.com/h5__test/task.html',
      app: '抖你',
      desc: 'tab、排行、弹窗、进度条、box',
    },
    {
      img: 'dn/taskDraw.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/taskDraw/App.vue',
      url: 'https://h5.douni.com/h5__test/taskDraw.html',
      app: '抖你',
      desc: '抽奖、弹幕、弹窗、进度条、记录',
    },
    {
      img: 'dn/upgradeBagGift.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/upgradeBagGift/App.vue',
      url: 'https://h5.douni.com/h5__test/upgradeBagGift.html',
      app: '抖你',
      desc: '半屏、抽奖、弹幕、轮播、swiper、记录',
    },
    {
      img: 'dn/vieHatRank.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/vieHatRank/App.vue',
      url: 'https://h5.douni.com/h5__test/vieHatRank.html',
      app: '抖你',
      desc: '半屏、排行、top',
    },
    {
      img: 'dn/honourRankingIndex.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/honourRankingIndex/App.vue',
      url: 'https://h5.douni.com/activities__test/honourRankingPkRoom.html',
      app: '抖你',
      desc: '榜单、排行、进度、弹窗、记录',
    },
    {
      img: 'dn/bingeBuy.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/bingeBuy/App.vue',
      url: 'https://h5.douni.com/activities__test/bingeBuy.html',
      app: '抖你',
      desc: '榜单、充值、排行、进度、弹窗、记录、兑换、前后',
    },
    {
      img: 'dn/travelWorldAsia.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/travelWorldAsia/App.vue',
      url: 'https://h5.douni.com/activities__test/travelWorldAsia.html',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后/计时',
    },
    {
      img: 'dn/loveTo.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/love2/App.vue',
      url: 'https://h5.douni.com/activities__test/love2.html',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、input',
    },
    {
      img: 'dn/preheat.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/ceremony/pageComponents/preheat.vue',
      url: 'https://h5.douni.com/activities__test/ceremony.html?p=preheat',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、input',
    },
    {
      img: 'dn/competition.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/ceremony/pageComponents/competition.vue',
      url: 'https://h5.douni.com/activities__test/ceremony.html?p=competition',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、input',
    },
    {
      img: 'dn/points.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/ceremony/pageComponents/points.vue',
      url: 'https://h5.douni.com/activities__test/ceremony.html?p=points',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、input',
    },
    //他她星球>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
      img: 'tt/horoscope.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/horoscope/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/horoscope.html?hidenavbar=1',
      app: '他她星球',
      desc: '弹幕、记录、input',
    },
    {
      img: 'tt/tree-hole.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/tree-hole/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/tree-hole.html?hidenavbar=1',
      app: '他她星球',
      desc: '列表、发送、input',
    },
    {
      img: 'tt/valentines23.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/valentines23/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/valentines23.html?hidenavbar=1',
      app: '他她星球',
      desc: '爱、榜单、进度、列表、发送、input',
    },
    {
      img: 'tt/goddess.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/goddess/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/goddess.html?hidenavbar=1',
      app: '他她星球',
      desc: '榜单',
    },
    {
      img: 'tt/mycall.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/mycall/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/mycall.html?hidenavbar=1',
      app: '他她星球',
      desc: '通话、语音、列表、box',
    },
    {
      img: 'tt/extractMan.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/extractMan/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/extractMan.html?hidenavbar=1',
      app: '他她星球',
      desc: '抽奖、轮播',
    },
    {
      img: 'tt/springLove.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/springLove/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/springLove.html?hidenavbar=1',
      app: '他她星球',
      desc: '榜单、进度、列表',
    },
    {
      img: 'tt/love23520.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/love23520/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/love23520.html?hidenavbar=1',
      app: '他她星球',
      desc: '爱、榜单、列表',
    },
    {
      img: 'tt/luckKitty.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/luckKitty/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/luckKitty.html?hidenavbar=1',
      app: '他她星球',
      desc: '爱、榜单、列表、进度、前后、弹窗',
    },
    {
      img: 'tt/workerDay.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/workerDay/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/workerDay.html?hidenavbar=1',
      app: '他她星球',
      desc: '劳动、兑换、充值、榜单、列表、搜索、input',
    },
    {
      img: 'tt/dragon23.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/dragon23/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/dragon23.html?hidenavbar=1',
      app: '他她星球',
      desc: '端午、爱、刮刮卡、榜单、列表、前后、计时',
    },
  ]
}
