export function uiList() {
  return [
    //抖你>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
      img: 'dn/level.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/myLevel/App.vue',
      url: 'https://h5.douni.com/h5__test/myLevel.html',
      app: '抖你',
      desc: '等级',
    },
    {
      img: 'dn/affinity.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/affinity/App.vue',
      url: 'https://h5.douni.com/h5__test/affinity.html',
      app: '抖你',
      desc: '亲密',
    },
    {
      img: 'dn/affinity2.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/affinity2/App.vue',
      url: 'https://h5.douni.com/h5__test/affinity2.html',
      app: '抖你',
      desc: '亲密、弹幕、swiper',
    },
    {
      img: 'dn/mbox.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/misteryBox/App.vue',
      url: 'https://h5.douni.com/h5__test/misteryBox.html',
      app: '抖你',
      desc: '盲盒、上传、弹幕、输入',
    },
    {
      img: 'dn/apar.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/apartment/App.vue',
      url: 'https://h5.douni.com/h5__test/apartment.html',
      app: '抖你',
      desc: '公寓、恋爱',
    },
    {
      img: 'dn/chicken.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/chicken/App.vue',
      url: 'https://h5.douni.com/h5__test/chicken.html',
      app: '抖你',
      desc: '榜单、tab、进度、PK',
    },
    {
      img: 'dn/card.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/bindCard/App.vue',
      url: 'https://h5.douni.com/h5__test/bindCard.html',
      app: '抖你',
      desc: '绑定、输入',
    },
    {
      img: 'dn/ggao.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/bulletin/App.vue',
      url: 'https://h5.douni.com/h5__test/bulletin.html',
      app: '抖你',
      desc: '公告、列表',
    },
    {
      img: 'dn/aicp.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/cp/App.vue',
      url: 'https://h5.douni.com/h5__test/cp.html',
      app: '抖你',
      desc: '公告、列表',
    },
    {
      img: 'dn/dtask.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/dayTask/App.vue',
      url: 'https://h5.douni.com/h5__test/dayTask.html',
      app: '抖你',
      desc: '半屏、任务、计时',
    },
    {
      img: 'dn/xdlottery.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/heartLottery/App.vue',
      url: 'https://h5.douni.com/h5__test/heartLottery.html',
      app: '抖你',
      desc: '抽奖、转动',
    },
    {
      img: 'dn/snow.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/iceSnow/App.vue',
      url: 'https://h5.douni.com/h5__test/iceSnow.html',
      app: '抖你',
      desc: '冰雪、领取、弹窗、明细',
    },
    {
      img: 'dn/papler.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/misteryBoxPapler/App.vue',
      url: 'https://h5.douni.com/h5__test/misteryBoxPapler.html',
      app: '抖你',
      desc: 'tab、明细、聊天、纸条',
    },
    {
      img: 'dn/nobility.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/nobility/App.vue',
      url: 'https://h5.douni.com/h5__test/nobility.html',
      app: '抖你',
      desc: '支付、弹窗、轮播、swiper、tab、明细',
    },
    {
      img: 'dn/plane.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/paperPlane/App.vue',
      url: 'https://h5.douni.com/h5__test/paperPlane.html',
      app: '抖你',
      desc: '弹窗、弹幕、tab、输入',
    },
    {
      img: 'dn/pay1.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/payReward/App.vue',
      url: 'https://h5.douni.com/h5__test/payReward.html',
      app: '抖你',
      desc: '弹窗、规则、box',
    },
    {
      img: 'dn/quality.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/quality/App.vue',
      url: 'https://h5.douni.com/h5__test/quality.html',
      app: '抖你',
      desc: '表格、兑换、box',
    },
    {
      img: 'dn/recharge.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/recharge/App.vue',
      url: 'https://h5.douni.com/h5__test/recharge.html',
      app: '抖你',
      desc: '充值、支付、box',
    },
    {
      img: 'dn/richClub.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/richClub/App.vue',
      url: 'https://h5.douni.com/h5__test/richClub.html',
      app: '抖你',
      desc: 'tab、排行、弹幕、弹窗、进度条、box',
    },
    {
      img: 'dn/task.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/task/App.vue',
      url: 'https://h5.douni.com/h5__test/task.html',
      app: '抖你',
      desc: 'tab、排行、弹窗、进度条、box',
    },
    {
      img: 'dn/taskDraw.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/taskDraw/App.vue',
      url: 'https://h5.douni.com/h5__test/taskDraw.html',
      app: '抖你',
      desc: '抽奖、弹幕、弹窗、进度条、记录',
    },
    {
      img: 'dn/upgradeBagGift.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/upgradeBagGift/App.vue',
      url: 'https://h5.douni.com/h5__test/upgradeBagGift.html',
      app: '抖你',
      desc: '半屏、抽奖、弹幕、轮播、swiper、记录',
    },
    {
      img: 'dn/vieHatRank.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/h5/blob/master/src/pages/vieHatRank/App.vue',
      url: 'https://h5.douni.com/h5__test/vieHatRank.html',
      app: '抖你',
      desc: '半屏、排行、top',
    },
    {
      img: 'dn/honourRankingIndex.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/honourRankingIndex/App.vue',
      url: 'https://h5.douni.com/activities__test/honourRankingPkRoom.html',
      app: '抖你',
      desc: '榜单、排行、进度、弹窗、记录',
    },
    {
      img: 'dn/bingeBuy.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/bingeBuy/App.vue',
      url: 'https://h5.douni.com/activities__test/bingeBuy.html',
      app: '抖你',
      desc: '榜单、充值、排行、进度、弹窗、记录、兑换、前后',
    },
    {
      img: 'dn/travelWorldAsia.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/travelWorldAsia/App.vue',
      url: 'https://h5.douni.com/activities__test/travelWorldAsia.html',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后/计时',
    },
    {
      img: 'dn/loveTo.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/love2/App.vue',
      url: 'https://h5.douni.com/activities__test/love2.html',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、输入',
    },
    {
      img: 'dn/preheat.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/ceremony/pageComponents/preheat.vue',
      url: 'https://h5.douni.com/activities__test/ceremony.html?p=preheat',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、输入',
    },
    {
      img: 'dn/competition.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/ceremony/pageComponents/competition.vue',
      url: 'https://h5.douni.com/activities__test/ceremony.html?p=competition',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、输入',
    },
    {
      img: 'dn/comluck.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/ceremony/components/points/luckyPop.vue',
      url: 'https://h5.douni.com/activities__test/ceremony.html?p=competition',
      app: '抖你',
      desc: '轮动、抽奖、转盘',
    },
    {
      img: 'dn/points.png',
      git: 'http://gitlab.tt.cn/xyzh5/shake-u/activities/blob/master/src/pages/ceremony/pageComponents/points.vue',
      url: 'https://h5.douni.com/activities__test/ceremony.html?p=points',
      app: '抖你',
      desc: '榜单、排行、进度、记录、前后、计时、输入',
    },
    //他她星球>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
      img: 'tt/horoscope.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/horoscope/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/horoscope.html?hidenavbar=1',
      app: '他她星球',
      desc: '弹幕、记录、输入',
    },
    {
      img: 'tt/tree-hole.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/tree-hole/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/tree-hole.html?hidenavbar=1',
      app: '他她星球',
      desc: '列表、发送、输入',
    },
    {
      img: 'tt/valentines23.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/valentines23/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/valentines23.html?hidenavbar=1',
      app: '他她星球',
      desc: '爱、榜单、进度、列表、发送、输入',
    },
    {
      img: 'tt/goddess.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/goddess/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/goddess.html?hidenavbar=1',
      app: '他她星球',
      desc: '榜单',
    },
    {
      img: 'tt/mycall.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/mycall/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/mycall.html?hidenavbar=1',
      app: '他她星球',
      desc: '通话、语音、列表、box',
    },
    {
      img: 'tt/extractMan.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/extractMan/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/extractMan.html?hidenavbar=1',
      app: '他她星球',
      desc: '抽奖、轮播',
    },
    {
      img: 'tt/springLove.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/springLove/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/springLove.html?hidenavbar=1',
      app: '他她星球',
      desc: '榜单、进度、列表',
    },
    {
      img: 'tt/love23520.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/love23520/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/love23520.html?hidenavbar=1',
      app: '他她星球',
      desc: '爱、榜单、列表',
    },
    {
      img: 'tt/luckKitty.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/luckKitty/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/luckKitty.html?hidenavbar=1',
      app: '他她星球',
      desc: '爱、榜单、列表、进度、前后、弹窗',
    },
    {
      img: 'tt/workerDay.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/workerDay/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/workerDay.html?hidenavbar=1',
      app: '他她星球',
      desc: '劳动、兑换、充值、榜单、列表、搜索、输入',
    },
    {
      img: 'tt/dragon23.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/dragon23/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/dragon23.html?hidenavbar=1',
      app: '他她星球',
      desc: '端午、爱、刮刮卡、榜单、列表、前后、计时',
    },
    {
      img: 'tt/misteryBox.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/misteryBox/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/misteryBox.html?hidenavbar=1',
      app: '他她星球',
      desc: '盲盒、爱、弹幕、列表',
    },
    {
      img: 'tt/peachBond.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/peachBond/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/peachBond.html?hidenavbar=1',
      app: '他她星球',
      desc: 'svga、爱、弹幕、列表',
    },
    {
      img: 'tt/idol.png',
      git: 'http://gitlab.tt.cn/xyzh5/his-planet/mass/blob/master/src/pages/allRank/App.vue',
      url: 'https://m.tataxingqiu.com/txqfe__test/mass/allRank.html?p=idol&hidenavbar=1',
      app: '他她星球',
      desc: 'svga、语音、礼物、弹幕、列表',
    },

    //轻甜>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
      img: 'qt/act38.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/act38/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe/mass/act38.html?isfullscreen=1&isstatusbar=1&hidenavbar=1&need_back=0',
      app: '轻甜',
      desc: '排行、进度、商店、输入',
    },
    {
      img: 'qt/act61.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/act61/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe/mass/act61.html?isfullscreen=1&isstatusbar=1&hidenavbar=1&need_back=0',
      app: '轻甜',
      desc: '排行、礼物',
    },
    {
      img: 'qt/act520.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/act520/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe/mass/act520.html?isfullscreen=1&isstatusbar=1&hidenavbar=1&need_back=0',
      app: '轻甜',
      desc: '排行、礼物、弹幕、进度、svga、计时',
    },
    {
      img: 'qt/act23520.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/activity_520/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe/mass/activity_520.html?isfullscreen=1&isstatusbar=1&hidenavbar=1&need_back=0',
      app: '轻甜',
      desc: '排行、礼物、弹幕、进度、svga、计时',
    },
    {
      img: 'qt/cprankList.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/cprankList/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/cprankList.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: 'tab、top、排行',
    },
    {
      img: 'qt/april-fools.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/april-fools/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/april-fools.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: 'tab、top、排行、进度、弹幕、轮播',
    },
    {
      img: 'qt/avenue-of-stars.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/avenue-of-stars/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/avenue-of-stars.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '抽奖、top、排行',
    },
    {
      img: 'qt/break-through.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/break-through/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/break-through.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '输入、top、排行、引导',
    },
    {
      img: 'qt/boatRace.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/boatRace/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/boatRace.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '送礼、top、排行、表格',
    },
    {
      img: 'qt/call-beast.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/call-beast/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/call-beast.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '召唤、神兽、top、排行、电连接',
    },
    {
      img: 'qt/christmas-give-like.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/christmas-give-like/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/christmas-give-like.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '圣诞、礼物、top、排行',
    },
    {
      img: 'qt/cloud_dream.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/cloud_dream/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/cloud_dream.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '元宵、礼盒、top、排行、记录',
    },
    {
      img: 'qt/eveningParty.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/eveningParty/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/eveningParty.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '周年、礼盒、top、排行、记录',
    },
    {
      img: 'qt/family-choose.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/family-choose/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/family-choose.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '家族、礼盒、top、排行、记录',
    },
    {
      img: 'qt/farmyard.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/farmyard/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/farmyard.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '小院种菜、礼盒、top、排行、记录',
    },
    {
      img: 'qt/ferris-wheel-rewards.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/ferris-wheel-rewards/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/ferris-wheel-rewards.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '摩天轮、转盘、礼盒、top、排行、记录',
    },
    {
      img: 'qt/gashapon.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/gashapon/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/gashapon.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '元宵、扭蛋机、礼盒、top、排行、记录、进度',
    },
    {
      img: 'qt/hamster.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/hamster/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/hamster.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '打地鼠、礼盒、音乐、top、排行、记录、进度',
    },
    {
      img: 'qt/highway.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/highway/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/highway.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '寻宝、礼盒、音乐、top、排行、记录、进度',
    },
    {
      img: 'qt/lantern.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/lantern/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/lantern.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '扭蛋、礼盒、轮播、top、排行、记录、进度',
    },
    {
      img: 'qt/lover-day.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/lover-day/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/lover-day.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '告白、礼物、top、排行、cp、进度',
    },
    {
      img: 'qt/sakuralove.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/sakuralove/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/sakuralove.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '告白、礼物、top、排行、cp、计时',
    },
    {
      img: 'qt/tanabata.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/tanabata/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/tanabata.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '七夕、礼物、top、排行、cp、计时',
    },
    {
      img: 'qt/topupGifts.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/topupGifts/App.vue',
      url: 'https://qingtian.tt.cn/qtappfe__test/mass/topupGifts.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '充值、礼物、抽取、排行、cp、计时',
    },
    {
      img: 'qt/520.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/520/App.vue',
      url: 'https://qingtian.tt.cn/fe__test/mass2/520/index.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: '转盘、礼物、排行、cp、进度',
    },
    {
      img: 'qt/family-pk.png',
      git: 'http://gitlab.tt.cn/xyzh5/qt/mass/blob/master/src/views/family-pk/App.vue',
      url: 'https://qingtian.tt.cn/fe__test/mass2/family-pk/index.html?isfullscreen=1&isstatusbar=1&hidenavbar=1',
      app: '轻甜',
      desc: 'PK、礼物、排行、cp、进度、计时',
    },
  ]
}
